// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package counterstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Counter struct {
	ID              int32
	Count           int32
	LastIncrementBy pgtype.Text
	LastIncrementAt pgtype.Timestamptz
	NextFinalizeAt  pgtype.Timestamptz
}

type IncrementRequest struct {
	RequestedBy string
	RequestedAt pgtype.Timestamptz
}

type Score struct {
	UserEmail string
	Score     int32
}

type User struct {
	ID    string
	Email string
}
