// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package counterstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetCounter(ctx context.Context, db DBTX) (Counter, error)
	IncrementCounter(ctx context.Context, db DBTX, arg IncrementCounterParams) error
	InsertIncrementRequest(ctx context.Context, db DBTX, arg InsertIncrementRequestParams) (int64, error)
	ListIncrementRequests(ctx context.Context, db DBTX) ([]IncrementRequest, error)
	ResetCounter(ctx context.Context, db DBTX) error
	TruncateIncrementRequests(ctx context.Context, db DBTX) error
	UpdateCounterFinalizeTime(ctx context.Context, db DBTX, nextFinalizeAt pgtype.Timestamptz) error
}

var _ Querier = (*Queries)(nil)
