swagger: "2.0"
info:
    title: Count Up
    description: A production-ready Go service deployed on Kubernetes
    version: 1.0.0
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        get:
            tags:
                - web
            summary: index web
            operationId: web#index
            produces:
                - text/html
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
            schemes:
                - http
    /another:
        get:
            tags:
                - web
            summary: another web
            operationId: web#another
            produces:
                - text/html
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
            schemes:
                - http
    /counter:
        get:
            tags:
                - api
            summary: CounterGet api
            operationId: api#CounterGet
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CounterInfo'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APICounterGetUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APICounterGetExistingIncrementRequestResponseBody'
            schemes:
                - http
    /counter/inc:
        post:
            tags:
                - api
            summary: CounterIncrement api
            operationId: api#CounterIncrement
            parameters:
                - name: CounterIncrementRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/APICounterIncrementRequestBody'
                    required:
                        - user
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/CounterInfo'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APICounterIncrementUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APICounterIncrementExistingIncrementRequestResponseBody'
            schemes:
                - http
    /echo:
        post:
            tags:
                - api
            summary: Echo api
            operationId: api#Echo
            parameters:
                - name: EchoRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/APIEchoRequestBody'
                    required:
                        - text
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/APIEchoResponseBody'
                        required:
                            - text
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APIEchoUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APIEchoExistingIncrementRequestResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - api
            summary: Download gen/http/openapi3.json
            operationId: api#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /static/{path}:
        get:
            tags:
                - web
            summary: Download static/
            operationId: web#/static/{*path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
                  type: string
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
                "404":
                    description: File not found
                    schema:
                        $ref: '#/definitions/Error'
            schemes:
                - http
definitions:
    APICounterGetExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterGet_existing_increment_request_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterGetUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterGet_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterIncrementExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterIncrement_existing_increment_request_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterIncrementRequestBody:
        title: APICounterIncrementRequestBody
        type: object
        properties:
            user:
                type: string
                example: Non perspiciatis eum dicta sit.
        example:
            user: Odio tenetur temporibus.
        required:
            - user
    APICounterIncrementUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterIncrement_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APIEchoExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Echo_existing_increment_request_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APIEchoRequestBody:
        title: APIEchoRequestBody
        type: object
        properties:
            text:
                type: string
                example: Deleniti necessitatibus numquam perspiciatis quia ipsa quam.
        example:
            text: Nemo dolorem ullam magnam.
        required:
            - text
    APIEchoResponseBody:
        title: APIEchoResponseBody
        type: object
        properties:
            text:
                type: string
                example: Praesentium qui debitis.
        example:
            text: Odit cum blanditiis ut.
        required:
            - text
    APIEchoUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Echo_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CounterInfo:
        title: 'Mediatype identifier: application/vnd.countup.counter-info`; view=default'
        type: object
        properties:
            count:
                type: integer
                example: 1315490442
                format: int32
            last_increment_at:
                type: string
                example: Eligendi quisquam.
            last_increment_by:
                type: string
                example: Vero molestiae.
            next_finalize_at:
                type: string
                example: Aut in dolor eum consequatur.
        description: CounterGetResponseBody result type (default view)
        example:
            count: 1162746042
            last_increment_at: Tempore asperiores.
            last_increment_by: Tempora repellendus.
            next_finalize_at: Quae voluptatibus dolor fugit quia.
        required:
            - count
            - last_increment_by
            - last_increment_at
            - next_finalize_at
    Error:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Error response result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
