[tools]
atlas = "0.29.0"
mkcert = "1.4.4"
go = "1.23.4"
golangci-lint = "1.62.2"
protoc = "29.1"
protoc-gen-go = "1.35.2"
protoc-gen-go-grpc = "1.5.1"
task = "3.40.1"
terraform = "1.5.7"

"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "1.27.0"
"go:goa.design/goa/v3/cmd/goa" = "3.19.1"
