// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userstore

import (
	"context"

	"github.com/jace-ys/countup/internal/idgen"
)

type Querier interface {
	GetUser(ctx context.Context, db DBTX, id idgen.ID[idgen.User]) (User, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	InsertUserIfNotExists(ctx context.Context, db DBTX, arg InsertUserIfNotExistsParams) error
}

var _ Querier = (*Queries)(nil)
