// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package userstore

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, db DBTX, id string) (User, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	InsertUserIfNotExists(ctx context.Context, db DBTX, arg InsertUserIfNotExistsParams) error
}

var _ Querier = (*Queries)(nil)
