---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
      - job_name: postgres
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [postgres]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 9187
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: grafana
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [grafana]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 3000
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: otel-collector
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [otel-collector]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 8888
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: promtail
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [promtail]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 3080
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: loki
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [loki]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 3100
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: tempo
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name 
            values: [tempo]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 3200
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

      - job_name: mimir
        scrape_interval: 30s
        docker_sd_configs:
        - host: unix:///var/run/docker.sock
          filters:
          - name: network
            values: [countup_default]
          - name: name
            values: [mimir]
        relabel_configs:
        - action: 'keep'
          source_labels: ['__meta_docker_port_private']
          regex: 3300
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'container_name'
        - source_labels: ['__meta_docker_container_name']
          regex: '/(.*)'
          target_label: 'service_name'

processors:
  batch:

  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

  tail_sampling:
    decision_wait: 30s
    policies:
    - name: sample-error-traces
      type: status_code
      status_code: {status_codes: [ERROR]}
    - name: sample-slow-traces
      type: latency
      latency: {threshold_ms: 200}

  transform/metadata:
    error_mode: ignore
    trace_statements:
    - context: resource
      statements:
      - set(attributes["deployment.environment.name"], "local")
    metric_statements:
    - context: resource
      statements:
      - set(attributes["deployment.environment.name"], "local")

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp/mimir:
    endpoint: http://mimir:3300/otlp
    tls:
      insecure: true

service:
  telemetry:
    logs:
      encoding: json

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker, transform/metadata]
      exporters: [otlp/tempo]

    metrics:
      receivers: [prometheus, otlp]
      processors: [batch, resourcedetection/docker, transform/metadata]
      exporters: [otlphttp/mimir]
