---
stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: warn
  log_format: json

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal
    pool:
      max_workers: 50
      queue_depth: 2000

distributor:
  receivers:
    otlp:
      protocols:
        grpc:

ingester:
  lifecycler:
    ring:
      replication_factor: 1

compactor:
  ring:
    kvstore:
      store: memberlist
  compaction:
    block_retention: 168h

metrics_generator:
  ring:
    kvstore:
      store: memberlist
  processor:
    span_metrics:
      dimensions:
      - service.version
      - tier
      - environment
      - endpoint.service
      - endpoint.method
      - http.method
      - http.target
      - http.status_code
      - rpc.service
      - rpc.method
      - rpc.grpc.status_code
      - job.worker
      - job.kind
      - job.queue
      - job.priority
    service_graphs:
      dimensions:
      - service.version
      - tier
      - environment
      - endpoint.service
      - endpoint.method
      - http.method
      - http.target
      - http.status_code
      - rpc.service
      - rpc.method
      - rpc.grpc.status_code
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/metrics-generator/wal
    remote_write:
    - url: http://mimir:3300/api/v1/push
      send_exemplars: true
  traces_storage:
    path: /tmp/tempo/metrics-generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      trace_id_label_name: trace_id
