{
 "title": "Service O11Y",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "endpoint_service",
    "label": "Endpoint Service",
    "query": {}
   },
   {
    "name": "endpoint_method",
    "label": "Endpoint Method",
    "query": {}
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": {}
   },
   {
    "name": "http_route",
    "label": "HTTP Route",
    "query": {}
   },
   {
    "name": "grpc_service",
    "label": "gRPC Service",
    "query": {}
   },
   {
    "name": "grpc_method",
    "label": "gRPC Method",
    "query": {}
   },
   {
    "name": "job_kind",
    "label": "Job Kind",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Log Level",
    "query": {}
   },
   { "name": "log_search", "label": "Log Search" }
  ]
 },
 "panels": [
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_runtime_go_goroutines{service=\"$service\", environment=\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg(rate(process_runtime_go_gc_pause_ns_bucket{service=\"$service\", environment=\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, avg(rate(process_runtime_go_gc_pause_ns_bucket{service=\"$service\", environment=\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Heap Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_runtime_go_mem_heap_alloc_bytes{service=\"$service\", environment=\"$environment\"})",
     "legendFormat": "alloc"
    },
    {
     "expr": "avg(process_runtime_go_mem_heap_inuse_bytes{service=\"$service\", environment=\"$environment\"})",
     "legendFormat": "in use"
    },
    {
     "expr": "avg(process_runtime_go_mem_heap_idle_bytes{service=\"$service\", environment=\"$environment\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Recovered Panics",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(go_panics_recovered_total{service=\"$service\", environment=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"goa.endpoint/.+\", goa_service=~\"$endpoint_service\", goa_method=~\"$endpoint_method\"}[$__rate_interval])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"goa.endpoint/.+\", goa_service=~\"$endpoint_service\", goa_method=~\"$endpoint_method\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"goa.endpoint/.+\", goa_service=~\"$endpoint_service\", goa_method=~\"$endpoint_method\"}[$__rate_interval])) by (span_name, status_code, le))",
     "legendFormat": "{{span_name}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "nodeGraph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (http_method, http_route) (rate(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_method, http_route) (increase(http_server_duration_milliseconds_sum{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range])) / sum by (http_method, http_route) (increase(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range])) by (http_method, http_route, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_method, http_route) (increase(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_method, http_route) (increase(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\", http_status_code=~\"2.*\"}[$__range])) / sum by (http_method, http_route) (increase(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_method, http_route)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\", http_status_code=~\"2..\"}[$__rate_interval])) by (http_method, http_route)",
     "legendFormat": "{{http_method}} {{http_route}} - 2XX"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\", http_status_code=~\"4..\"}[$__rate_interval])) by (http_method, http_route)",
     "legendFormat": "{{http_method}} {{http_route}} - 4XX"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\", http_status_code=~\"5..\"}[$__rate_interval])) by (http_method, http_route)",
     "legendFormat": "{{http_method}} {{http_route}} - 5XX"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__rate_interval])) by (http_method, http_route, le))",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", http_method=~\"$http_method\", http_route=~\"$http_route\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name = \"$service\" && resource.environment = \"$environment\" && span.http.method=~\"$http_method\" && span.http.route=~\"$http_route\" && status = error } || { resource.service.name = \"$service\" && resource.environment = \"$environment\" && span.http.method=~\"$http_method\" && span.http.route=~\"$http_route\" } >> { status = error }",
     "tableType": "traces"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (rpc_service, rpc_method) (rate(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (rpc_service, rpc_method) (increase(rpc_server_duration_milliseconds_sum{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range])) / sum by (rpc_service, rpc_method) (increase(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95, sum(rate(rpc_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range])) by (rpc_service, rpc_method, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (rpc_service, rpc_method) (increase(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (rpc_service, rpc_method) (increase(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\", rpc_grpc_status_code=\"0\"}[$__range])) / sum by (rpc_service, rpc_method) (increase(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__rate_interval])) by (rpc_service, rpc_method)",
     "legendFormat": "{{rpc_service}} {{rpc_method}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\", rpc_grpc_status_code=\"0\"}[$__rate_interval])) by (rpc_service, rpc_method)",
     "legendFormat": "{{rpc_service}} {{rpc_method}} - Ok"
    },
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\", rpc_grpc_status_code!=\"0\"}[$__rate_interval])) by (rpc_service, rpc_method, rpc_grpc_status_code)",
     "legendFormat": "{{rpc_service}} {{rpc_method}} - {{rpc_grpc_status_code}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(rpc_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__rate_interval])) by (rpc_service, rpc_method, le))",
     "legendFormat": "{{rpc_service}} {{rpc_method}}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rpc_server_duration_milliseconds_bucket{service=\"$service\", environment=\"$environment\", rpc_service=~\"$grpc_service\", rpc_method=~\"$grpc_method\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name = \"$service\" && resource.environment = \"$environment\" && kind = server && span.rpc.service=~\"$grpc_service\" && span.rpc.method=~\"$grpc_method\" && status = error } || { resource.service.name = \"$service\" && resource.environment = \"$environment\" && kind = server && span.rpc.service=~\"$grpc_service\" && span.rpc.method=~\"$grpc_method\" } >> { status = error }",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Available Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (worker_jobs_available_count{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"})",
     "legendFormat": "Available: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    }
   ]
  },
  {
   "title": "Jobs Enqueued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (increase(worker_jobs_enqueued_total{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval]))",
     "legendFormat": "Enqueued: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (increase(worker_jobs_completed_total{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval]))",
     "legendFormat": "Completed: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    },
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (increase(worker_jobs_discarded_total{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval]))",
     "legendFormat": "Discarded: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    },
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (increase(worker_jobs_cancelled_total{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval]))",
     "legendFormat": "Cancelled: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by (job_kind, job_queue, job_priority) (increase(worker_jobs_failed_total{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval]))",
     "legendFormat": "Failed: {{job_kind}} - {{job_queue}}[{{job_priority}}]"
    }
   ]
  },
  {
   "title": "Job Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"river.worker/.*\", job_kind=~\"$job_kind\"}[$__rate_interval])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"river.worker/.*\", job_kind=~\"$job_kind\"}[$__rate_interval])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Job Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service=\"$service\", environment=\"$environment\", span_kind=\"SPAN_KIND_INTERNAL\", span_name=~\"river.worker/.*\", job_kind=~\"$job_kind\"}[$__rate_interval])) by (span_name, status_code, le))",
     "legendFormat": "{{span_name}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "P95 Queue Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(worker_jobs_queue_wait_milliseconds_bucket{service=\"$service\", environment=\"$environment\", job_kind=~\"$job_kind\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name = \"$service\" && resource.environment = \"$environment\" && span.job.kind =~ \"$job_kind\" && status = error } || { resource.service.name = \"$service\" && resource.environment = \"$environment\" && span.job.kind =~ \"$job_kind\" } >> { status = error }",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"})[$__auto]))"
    }
   ]
  },
  {
   "title": "Log Volume by File",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 151 },
   "targets": [
    {
     "expr": "topk(5, sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"} | json | __error__=\"\")[$__auto])) by (file))",
     "legendFormat": "{{file}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"} | json | detected_level = \"error\")[$__auto]))"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"} | json | __error__=\"\")[$__auto])) by (detected_level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs by Level",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"} | json | __error__=\"\")[$__range])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Logs by Stream",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service\", environment=\"$environment\"})[$__range])) by (logstream)",
     "legendFormat": "{{logstream}}"
    }
   ]
  },
  {
   "title": "Logs (Searchable)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "{service_name=\"$service\", environment=\"$environment\"} | json | line_format `{{__line__}}` | detected_level=~\"$log_level\" |~ \"(?i).*($log_search).*\""
    }
   ]
  }
 ]
}