// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package scorestore

import (
	"context"
)

type Querier interface {
	InsertScore(ctx context.Context, db DBTX, arg InsertScoreParams) error
	ListScores(ctx context.Context, db DBTX) ([]Score, error)
}

var _ Querier = (*Queries)(nil)
