---
name: app

on: push

defaults:
  run:
    working-directory: ./app

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        version: 2024.10.7
        install: true
        install_args: 'atlas task'
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
    - run: go mod tidy
    - name: check-diff
      run: if [[ -n $(git status --porcelain) ]]; then git status --porcelain && exit 1; fi
