---
name: app

on: [push]

defaults:
  run:
    working-directory: ./app

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        version: 2025.8.21
        install: true
        experimental: true
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24.6'
        cache-dependency-path: 'app/go.sum'
    - run: go mod tidy
    - run: task gen
    - name: Save task cache
      uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ./.task
        key: task-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.task/checksum/*') }}
    - name: Check git status
      run: if [[ -n $(git status --porcelain) ]]; then git status --porcelain && exit 1; fi

  lint:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Restore task cache
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ./.task
        key: task-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.task/checksum/*') }}
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        version: 2025.8.21
        install: false
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24.6'
        cache-dependency-path: 'app/go.sum'
    - uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
      with:
        version: v1.64.8
        working-directory: ./app
        args: --path-prefix=./

  test:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Restore task cache
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ./.task
        key: task-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.task/checksum/*') }}
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        version: 2025.8.21
        install: false
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24.6'
        cache-dependency-path: 'app/go.sum'
    - run: task test

  build:
    needs: [prepare]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Restore task cache
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ./.task
        key: task-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.task/checksum/*') }}
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      with:
        version: 2025.8.21
        install: false
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '1.24.6'
        cache-dependency-path: 'app/go.sum'
    - run: task build
